In [2]:
import numpy as np
arr_2d = np.array([[40.5 , 45.5 , 50.3 , 58.5] , [4, 5, 6, 8]])
arr_2d[0][1]

np.float64(45.5)

In [4]:
arr_2d[: ,1:3]

array([[45.5, 50.3],
       [ 5. ,  6. ]])

In [5]:
np.mean(arr_2d[:,0])

np.float64(22.25)

In [6]:
np.median(arr_2d[:,1])

np.float64(25.25)

In [13]:
np.sort(arr_2d[:,0])

array([ 4. , 40.5])

In [16]:
np.sort(arr_2d[:,:])

array([[40.5, 45.5, 50.3, 58.5],
       [ 4. ,  5. ,  6. ,  8. ]])

In [22]:
np.random.randint(1,5,10)

array([1, 1, 4, 3, 4, 2, 3, 3, 4, 4], dtype=int32)

In [23]:
height = np.round(np.random.normal(1.75 , 0.20 , 5000)10)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4207071655.py, line 1)